name: patch-yaml-through-commit
author: Roman Lakhtadyr <roman.lakhtadyr@gmail.com>
description: A Github Action that allows patching yaml files in the other repository and commit changes.
inputs:
  git_repo_url:
    description: Git repository to connect.
    required: true
  git_branch:
    description: Git repository branch to checkout from.
    required: false
    default: master
  committer_name:
    description: Name on whose behalf a commit will be made.
    required: false
    default: John Doe
  committer_email:
    description: Email on whose behalf a commit will be made.
    required: false
    default: pldin601@gmail.com
  commit_message:
    description: Message for commit.
    required: true
  yaml_file:
    description: Path to yaml file which should be patched (related to repository's root).
    required: true
  patch_expression:
    description: Space-separated pairs of path.to.node=value expresions to patch.
    required: true
  dry_run:
    description: If this parameter set, no commit will be made. Just generated diff.
    required: false
runs:
  using: docker
  image: Dockerfile
branding:
  icon: droplet
  color: blue
